search/__init__.py
import configparser

config = configparser.ConfigParser()
config.read('config.ini', 'utf-8')
DIR_PATH = config['DEFAULT']['doc_dir_path']
DIR_CONCEPT_PATH = config['DEFAULT']['concept_dir_path']
COURSEDB_PATH = config['DEFAULT']['db_path'] #added 
CONFIG_PATH = 'config.ini'

search/controllers.py
from flask import Blueprint, request, render_template, \
    flash, g, session, redirect, url_for

from search.utils import cut_page, find, searchidlist, \
    get_k_nearest, find_concept
from search.search_engine import SearchEngine
from search import CONFIG_PATH
from __init__ import browse_categories
import json

# Define the blueprint: 'search', and set its url prefix: search
searcher = Blueprint('searcher', __name__, url_prefix='/search/')

def error_page():
    return render_template('search.html', nonempty=False, welcome=False, browse_categories=browse_categories)


@searcher.route('/', methods=['POST'])
def search():
    """
    Implements search functionality to find courses.
    Input: (via POST)
        - Form containing:
            * key_word

    :return:
        HTML template with the results.
    """

    try:
        checked = ['checked="true"', '', '']
        keys = request.form['key_word']
        category = request.form['search_field']
        session['checked'] = checked
        session['keys'] = keys

        if keys not in ['']:
            flag, page, docid = searchidlist(keys)
            session['page'] = page
            session['s_flag'] = flag
            session['doc_id'] = docid

            if flag == 0:
                return render_template('search.html', nonempty=False, welcome=False,
                                       browse_categories=browse_categories)

            docs = cut_page(page, 0, docid)

            docs_concept = find_concept([keys.replace(" ", "_")], extra=True)
            if docs_concept:
                        docs_concept = docs_concept[0]
                        docs_concept["concept_name"] = docs_concept["concept_name"].title()
                        show_concept = True
            else:
                        show_concept = False

            return render_template('high_search.html', checked=checked, key=keys, docs=docs,concept=docs_concept, page=page,
                                   nonempty=True, welcome=False,showconcept = show_concept, browse_categories=browse_categories)
        else:
            return render_template('search.html', nonempty=False, welcome=True, browse_categories=browse_categories)

    except Exception as e:
        print('search error')
        print(e)
        return render_template('search.html', nonempty=False, welcome=True, browse_categories=browse_categories)


@searcher.route('page/<page_no>/', methods=['GET'])
def next_page(page_no):
    """

    :param page_no:
    :return:
    """
    page, checked, docid = session['page'], session['checked'], session['doc_id']
    try:
        page_no = int(page_no)
        docs = cut_page(page, (page_no - 1), docid)
        return render_template('high_search.html', checked=checked, key=session['keys'], docs=docs, page=page,
                               nonempty=True, welcome=False, browse_categories=browse_categories)
    except:
        print('next error')

@searcher.route('concepts/<id>/', methods=['GET', 'POST'])
def content_concept(id):
    """
    Fetch concept content with document id = id.
    :param id:
    :return:
    """
    try:
        doc = find_concept([id], extra=True)
        return render_template('concept.html', doc=doc[0])
    except Exception as e:
        print('content error' + str(e))
        return error_page()

@searcher.route('/<id>/', methods=['GET', 'POST'])
def content(id):
    """
        Fetch content with document id = id.
    :param id:
    :return:
    """
    try:
        doc = find([id], extra=True)
        return render_template('content.html', doc=doc[0])
    except Exception as e:
        print('content error' +str(e))


@searcher.route('/search/<key>/', methods=['POST','GET'])
def high_search(key):
    """

    :param key:
    :return:
    """
    # REVIEW:
    # The errors should throw a 404 or a 500.
    # Not die silently.
    try:

        selected = int(request.form['order'])
        for i in range(3):
            if i == selected:
                session['checked'][i] = 'checked="true"'
            else:
                session['checked'][i] = ''
        flag, page, docid = searchidlist(key, selected)
        session['s_flag'] = flag
        session['page'] = page
        session['doc_id'] = docid
        if flag == 0:
            return render_template('search.html', nonempty=False, welcome=False)
        docs = cut_page(page, 0)
        return render_template('high_search.html', checked=session['checked'], key=session['keys'], docs=docs, page=page,
                               nonempty=True, welcome=False)
    except:
        print('high search error')


@searcher.route('search_keyword/', methods=['POST', 'GET'])
@searcher.route('/search_keyword/<key>/', methods=['POST','GET'])
def search_keyword(key = None):
    """
    Implements search functionality to find courses.

    :return:
        HTML template with the results.
    """
    try:

        checked = ['checked="true"', '', '']
        keys =key
        session['checked'] = checked
        session['keys'] = keys

        if keys not in ['']:
            flag, page, docid = searchidlist(keys)
            session['page'] = page
            session['s_flag'] = flag
            session['doc_id'] = docid

            if flag == 0:
                return render_template('search.html', nonempty=False, welcome=False,
                                       browse_categories=browse_categories)

            docs = cut_page(page, 0, docid)

            docs_concept = find_concept([keys.replace(" ", "_")], extra=True)
            if docs_concept:
                        docs_concept = docs_concept[0]
                        docs_concept["concept_name"] = docs_concept["concept_name"].title()
                        show_concept = True
            else:
                        show_concept = False

            return render_template('high_search.html', checked=checked, key=keys, docs=docs,concept=docs_concept, page=page,
                                   nonempty=True, welcome=False,showconcept = show_concept, browse_categories=browse_categories)
        else:
            return render_template('search.html', nonempty=False, welcome=True, browse_categories=browse_categories)

    except Exception as e:
        print('search keyword error')
        print(e)
        return render_template('search.html', nonempty=False, welcome=True, browse_categories=browse_categories)

visualization/controllers.py
"""
controllers.py
====================
Functionality in visualization: click on the concept button, show the visualization of the concept graph.
"""
from visualization.__init__ import *
from __init__ import concept_dict


visualizer = Blueprint('visualizer', __name__)

@visualizer.route('/concepts')
def showing_concepts():
    """
     The front-end interaction part. Render to the visualize.html webpage.

    """
    g.name = "information science"
    return render_template('visualize.html')


@visualizer.route('/concept_pure',methods=['GET', 'POST'])
def concept_visualize():
    """
    Draw the concept graph

    """
    g.concept = concept_dict["children"]
    return render_template('concept_visualize.html')

@visualizer.route('/aboutEduAI',methods=['GET', 'POST'])
def aboutEduAI():
    """
    Route to the aboutEduAI page

    """

    return render_template('aboutEduAI.html')


@visualizer.route('/contact',methods=['GET', 'POST'])
def contact():
    """
    Route to the contact page

    """

    return render_template('contact.html')

templates/aboutEduAI.html
{% extends "basetemplate.html" %}
{% block title %}EdA About{% endblock %}
{% block additional_static %}
    <link href="{{ url_for('static', filename='css/offcanvas.css') }}" type="text/css" rel="stylesheet">
{% endblock %}
{% block page_content %}
    <main role="main" class="container">


      <div class="my-3 p-3 bg-white rounded box-shadow">
        <h4 class="border-bottom border-gray pb-2 mb-0">About this website</h4>
        <div class="media text-muted pt-3">
          <p class="media-body pb-10 mb-0 large lh-125 border-bottom border-gray">
           Welcome to Education AI! We are here to help you learn and explore MOOCs in a more efficient way. Below are two novel features that we have!
              <br />
              <br />
              1.Here, you can explore MOOCs based on knowledge concept dependencies. EduAI will build knowledge graphs consisting of the search-related concepts and their prerequisite relations.  When you decides to learn a competency, our system guides the learning process by suggesting the appropriate MOOCs following the prerequisite order.
          <br />
              <br />
              2.Personalized learning. Learners have various backgrounds, and traditional platforms ignore this diversity by suggesting the same courses for every learner. For instance, a user with a mathematics degree would take very little away from a linear algebra introduction in a machine learning competency track.  To make the learning process more personally relevant, our website will offer a user management system that takes every learner’s background into consideration to provide knowledge concepts and courses in a personalized way.
          </p>
        </div>
      </div>

      <div class="my-3 p-3 bg-white rounded box-shadow">
        <h4 class="border-bottom border-gray pb-2 mb-0">Recent Updates</h4>
        <div class="media text-muted pt-3">
          <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
          <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <div class="d-flex justify-content-between align-items-center w-100">
              <strong class="text-gray-dark">Concept Graph</strong>
              <a href="{{url_for('visualizer.showing_concepts')}}">Check it out!</a>
            </div>
            <span class="d-block">@Zijie Huang</span>
          </div>
        </div>
        <div class="media text-muted pt-3">
          <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
          <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <div class="d-flex justify-content-between align-items-center w-100">
              <strong class="text-gray-dark">Browse Mode</strong>
              <a href="/">Check it out!</a>
            </div>
            <span class="d-block">@Zijie Huang</span>
          </div>
        </div>
        <div class="media text-muted pt-3">
          <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
          <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <div class="d-flex justify-content-between align-items-center w-100">
              <strong class="text-gray-dark">Contact Us</strong>
              <a href="contact">Check it out!</a>
            </div>
            <span class="d-block">@Zijie Huang</span>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

templates/concept.html
{% extends "basetemplate.html" %}
{% block title %}{{doc.course_name}}{% endblock %}
{% block page_content %}
  <!--main role="main" class="container overflow-auto fixed_height"-->
  <main role="main" class="overflow-auto fixed_height">
  <div class="padded_content">
    <div id="basic" align="center">
        <h1>{{doc.concept_name}}</h1>
    </div>
    <br/>
    <hr/>
    <div id="detail" align="center">
        <table width="1000" border="0">
            <tr> <h4>Introduction:</h4>
            </tr>
            <tr>
                <td style="width:1000px"><p>{{doc.wiki}}</p></td>
            </tr>
        </table>
    </div>
    <div align="center">
        <table width="1000" border="0">
            <tr>
                <td style="width:1000px"><h2>Related Courses</h2></td>
            </tr>
            <!--{% for each in doc.extra %}
            <tr>
                <td style="width:1000px"><a href="/search/{{each.id}}/" target="_blank">{{each.title}}</a></td>
            </tr>
            {% endfor %} -->
        </table>
    </div>
  </div>
  </main>
{% endblock %}

templates/concept_visualize.html
<!DOCTYPE html>
<meta charset="utf-8">
<head>
    <!--The font-awesome stylesheet has to be online-->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" type="text/css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/bootstrap-select.min.css') }}" type="text/css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/jquery-ui.css') }}" type="text/css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/customized_layout.css') }}" type="text/css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/chatbox_layout.css') }}" type="text/css" rel="stylesheet">
    <script src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/tooltip.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/bootstrap-select.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/bootstrap-toolkit.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/jquery-ui.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/frontend_interaction.js') }}" type="text/javascript"></script>
</head>
<style>

.node circle {
  cursor: pointer;
  stroke: #bbbcbd;
  stroke-width: 1.5px;
}

.node text {
  font: 14px sans-serif;
  pointer-events: none;
  text-anchor: middle;
}

line.link {
  fill: none;
  stroke: rgba(187, 188, 189, 0.9);
  stroke-width: 1.5px;
}

</style>
<body>
<div class="container">
      <div class="row" id="1">
      </div>
    </div>
<script src="//d3js.org/d3.v3.min.js"></script>
<script>

var width = window.innerWidth,
    height = window.innerHeight,
    color = d3.scale.category10(),
    root;

var force = d3.layout.force()
    .linkDistance(110)
    .charge(-100)
    .gravity(.005)
    .size([width, height])
    .on("tick", tick);

var svg = d3.select("body").append("svg")
    .attr("width", width)
    .attr("height", height);

var link = svg.selectAll(".link"),
    node = svg.selectAll(".node");


var root = {
 "name": "Concepts",
 "children": [
    {
     "name": "Information Science",
     "children": [
      {"name": "Data Mining",
       "children": [
        {"name": "Data Analysis", "group":2, "level":4},
        {"name": "Probability and Mathematical Statistics Model", "group":2, "level":4},
        {"name": "Data Mining Applications", "group":2, "level":4}
        ],
       "group":2,
       "level":3},
      {"name": "The Web & Information Retrieval",
       "children": [
        {"name": "Intelligent Information Systems", "group":2, "level":4},
        {"name": "Web information Systems", "group":2, "level":4},
        {"name": "Web Applications", "group":2, "level":4},
        {"name": "Mobile and Web Development", "group":2, "level":4}
        ],
       "group":2,
       "level":3},
      {"name": "Database",
       "children": [
        {"name": "Data Management", "group":2, "level":4},
        {"name": "Database Systems", "group":2, "level":4}
      ],
       "group":2,
       "level":3},
      {"name": "Information Theory", "group":2, "level":3}
     ],
      "group": 2,
      "level": 2
    },
    {
     "name": "Networking",
     "children": [
      {"name": "Wireless Systems", "group":3, "level":3},
      {"name": "Mobile Computing",  "group":3, "level":3},
      {"name": "Data Communications", "group":3, "level":3},
       {"name": "Cloud Computing", "group":3, "level":3},
       {"name": "Network development", "group":3, "level":3}
     ],
      "group": 3,
 "level": 2
    },
    {
     "name": "Computer Theory",
     "children": [
      {"name": "Logic and Verification", "group":4, "level":3},
      {"name": "Algorithms and Complexity", "group":4, "level":3},
      {"name": "Data Structure and Algorithms", "group":4, "level":3}
     ],
      "group": 4,
 "level": 2
    },
   {
     "name": "Artificial Intelligence",
     "children": [
      {"name": "Natural Language Processing", "group":5, "level":3},
      {"name": "Computer Vision", "group":5, "level":3},
      {"name": "Machine Learning", "group":5, "level":3}
     ],
      "group": 5,
 "level": 2
    }
 ],
 "group": 1,
 "level": 1
};




update();
function update() {
  var nodes = flatten(root),
      links = d3.layout.tree().links(nodes);

  // Restart the force layout.
  force
      .nodes(nodes)
      .links(links)
      .start();

  // Update links.
  link = link.data(links, function(d) { return d.target.id; });

  link.exit().remove();

  link.enter().insert("line", ".node")
      .attr("class", "link");

  // Update nodes.
  node = node.data(nodes, function(d) { return d.id; });

  node.exit().remove();

  var nodeEnter = node.enter().append("g")
      .attr("class", "node")
      .on("click", click)
      .call(force.drag);

  nodeEnter.append("circle")
      .attr("r", function(d) { return 1.0/ d.level * 40; });

  nodeEnter.append("text")
      .attr("dy", ".35em")
      .text(function(d) { return d.name; });

  node.select("circle")
      .style("fill", function(d) {var current_color = color(d.group); console.log(current_color); return current_color;});
}

function tick() {
  link.attr("x1", function(d) { return d.source.x; })
      .attr("y1", function(d) { return d.source.y; })
      .attr("x2", function(d) { return d.target.x; })
      .attr("y2", function(d) { return d.target.y; });

  node.attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; });
}




function showcontent(d) {
    var content_div = document.getElementById("1");
    content_div.innerHTML = ""; // clear
    var tmpcontent_element = generate_d_element(d)
    content_div.appendChild(tmpcontent_element);
}



function generate_d_element (d) {
  var container = document.createElement('div');
  container.className = "col-md-4";
  var button_container = document.createElement('p');
  var button = document.createElement('a');
  button.className = "btn btn-secondary";
  button.innerHTML = "Plunge deeper into " + d.name;
  button.setAttribute("href", "{{url_for('searcher.search_keyword')}}" + d.name);
  button.setAttribute("role", "button");
  button_container.appendChild(button);
  container.appendChild(button_container);
  return container;
}


function showresult(d) {
    var data = {
    data: JSON.stringify({
      "name": d.name
    })
  };
  $.ajax({
      url: "/search_keyword" ,
      type: "POST",
      data: data,
      dataType: 'json',
      success: function(data) {
      },
      error: function(xhr, type) {
        console.log("error", xhr, type);
      }
  });
}

// Toggle children on click.
function click(d) {
  if (d3.event.defaultPrevented) return; // ignore drag
  if (d.children) {
    d._children = d.children;
    d.children = null;
  } else {
    d.children = d._children;
    d._children = null;
  }
  update();
  if (d.name != "Concepts") {
        showcontent(d);
  }
}

// Returns a list of all nodes under the root.
function flatten(root) {
  var nodes = [], i = 0;

  function recurse(node) {
    if (node.children) node.children.forEach(recurse);
    if (!node.id) node.id = ++i;
    nodes.push(node);
  }

  recurse(root);
  return nodes;
}

</script>

templates/contact.html
{% extends "basetemplate.html" %}
{% block title %}EdA About{% endblock %}
{% block additional_static %}
    <link href="{{ url_for('static', filename='css/floating-labels.css') }}" type="text/css" rel="stylesheet">
{% endblock %}
{% block page_content %}
    <form class="form-signin-contact">
      <div class="text-center mb-4">
        <img class="mb-4" src="/static/img/logo.png" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">Education AI </h1>
        <p align="left"><b>This work is done by team-A3 in CS131 Winter Quarter, 2020, in UCLA. </b><br />
        <b>Our team members: Jiang Song, Zijie Huang, Junyu Guo, Zixuan Lu, Yugo Watanabe, Kaiyuan Chen</b></p>
      </div>

      <div class="form-label-group">
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputEmail">Your Email Address</label>
      </div>

      <div class="form-label-group-contact">
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" placeholder="Suggestions and Problems"></textarea>
          <label for="Suggestions and Problems"></label>
      </div>

      <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
      <p class="mt-5 mb-3 text-muted text-center">&copy; 2020.1-2020.3</p>
    </form>
{% endblock %}

templates/content.html
{% extends "basetemplate.html" %}
{% block title %}{{doc.course_name}}{% endblock %}
{% block page_content %}
  <!--main role="main" class="container overflow-auto fixed_height"-->
  <main role="main" class="overflow-auto fixed_height">
  <div class="padded_content">
    <div id="basic" align="center">
        <h1>{{doc.course_name}}</h1>
        <h4>Instructor: {{doc.course_instructor}} </h4>
        <h4>Affiliation: {{doc.course_orgnization}}</h4>
        <p>Platform: {{doc.course_platform}}
        <p>Time: {{doc.course_time}}</p>
        <p><a href="{{doc.course_url}}" target="_blank">{{doc.course_url}}</a></p>
    </div>
    <br/>
    <div id="tag" class="container">
      <p>Course Category: {{doc.course_category}}
      <P>Course Tag: {{doc.course_tag}}
      <p>Course Rating: {{doc.course_rating}}
    </div>
    <hr/>
    {% for video_url in doc.video_urls %}
    <div class="container" align="center">
        <iframe width="560" height="315" src="{{video_url}}" frameborder="0" allowfullscreen=""></iframe>
    </div>
    <hr/>
    {% endfor %}
    <div id="detail" align="center">
        <table width="1000" border="0">
            <tr> <h4>Introduction:</h4>
            </tr>
            <tr>
                <td style="width:1000px"><p>{{doc.course_introduction}}</p></td>
            </tr>
        </table>
    </div>
    <hr/>
    <div class="container">
        <h5>Chapter:</h5>
        <ul>
        {% for chapter in doc.course_chapter %}
            <li><h6>{{chapter}}</h6></li>
        {% endfor %}
        </ul>
    </div>
    <hr/>
    <div class="container">
        <h5>Reviews:</h5>
        <!--for now it doesn't work since it is a string-->
        <ul>
        {% for review in doc.reviews %} 
            <li><h6>{{review}}</h6></li>
        {% endfor %}
        </ul>
    </div>
    <div align="center">
        <table width="1000" border="0">
            <tr>
                <td style="width:1000px"><h2>Related Courses</h2></td>
            </tr>
            <!--{% for each in doc.extra %}
            <tr>
                <td style="width:1000px"><a href="/search/{{each.id}}/" target="_blank">{{each.title}}</a></td>
            </tr>
            {% endfor %} -->
        </table>
    </div>
  </div>
  </main>
{% endblock %}

templates/high_search.html
{% extends "search.html" %}
{% block high_search%}
<div id="select">
    <ul>
        <form action="/search/key/{{key}}/" method="POST">
        	<input type=hidden name=form_name value="search_option"/>
            <input {{checked[0]}} type="radio" name="order" id="r1" value="0" /> <label for="r1">Relevence</label>
            <input {{checked[1]}} type="radio" name="order" id="r2" value="1" /> <label for="r2">Popularity</label>
       <!-- <button class="btn" type="submit" style="background-color:transparent"><img src="{{ url_for('static', filename='img/sort.png') }}"></button> -->
        </form>
    </ul>
</div>
{% endblock %}

templates/visualize.html
{% extends "basetemplate.html" %}
{% block title %}EdA Visualization{% endblock %}
{% block additional_static %}
    <script src="{{ url_for('static', filename='js/d3.v3.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/d3.legend.js') }}" type="text/javascript"></script>
{% endblock %}
{% block page_content %}
    <style>

.node circle {
  cursor: pointer;
  stroke: #bbbcbd;
  stroke-width: 1.5px;
}

.node text {
  font: 14px sans-serif;
  pointer-events: none;
  text-anchor: middle;
}

line.link {
  fill: none;
  stroke: rgba(187, 188, 189, 0.9);
  stroke-width: 1.5px;
}

</style>

    <div class="container">
      <div class="row" id="1">
      </div>
    </div>
<script src="//d3js.org/d3.v3.min.js"></script>
<script>

var width = window.innerWidth,
    height = window.innerHeight,
    color = d3.scale.category10(),
    root;

var force = d3.layout.force()
    .linkDistance(110)
    .charge(-100)
    .gravity(.005)
    .size([width, height])
    .on("tick", tick);

var svg = d3.select("body").append("svg")
    .attr("width", width)
    .attr("height", height);

var link = svg.selectAll(".link"),
    node = svg.selectAll(".node");


var root = {
 "name": "Concepts",
 "children": [
    {
     "name": "Information Science",
     "children": [
      {"name": "Data Mining",
       "children": [
        {"name": "Data Analysis", "group":2, "level":4},
        {"name": "Probability and Mathematical Statistics Model", "group":2, "level":4},
        {"name": "Data Mining Applications", "group":2, "level":4}
        ],
       "group":2,
       "level":3},
      {"name": "The Web & Information Retrieval",
       "children": [
        {"name": "Intelligent Information Systems", "group":2, "level":4},
        {"name": "Web information Systems", "group":2, "level":4},
        {"name": "Web Applications", "group":2, "level":4},
        {"name": "Mobile and Web Development", "group":2, "level":4}
        ],
       "group":2,
       "level":3},
      {"name": "Database",
       "children": [
        {"name": "Data Management", "group":2, "level":4},
        {"name": "Database Systems", "group":2, "level":4}
      ],
       "group":2,
       "level":3},
      {"name": "Information Theory", "group":2, "level":3}
     ],
      "group": 2,
      "level": 2
    },
    {
     "name": "Networking",
     "children": [
      {"name": "Wireless Systems", "group":3, "level":3},
      {"name": "Mobile Computing",  "group":3, "level":3},
      {"name": "Data Communications", "group":3, "level":3},
       {"name": "Cloud Computing", "group":3, "level":3},
       {"name": "Network development", "group":3, "level":3}
     ],
      "group": 3,
 "level": 2
    },
    {
     "name": "Computer Theory",
     "children": [
      {"name": "Logic and Verification", "group":4, "level":3},
      {"name": "Algorithms and Complexity", "group":4, "level":3},
      {"name": "Data Structure and Algorithms", "group":4, "level":3}
     ],
      "group": 4,
 "level": 2
    },
   {
     "name": "Artificial Intelligence",
     "children": [
      {"name": "Natural Language Processing", "group":5, "level":3},
      {"name": "Computer Vision", "group":5, "level":3},
      {"name": "Machine Learning", "group":5, "level":3}
     ],
      "group": 5,
 "level": 2
    }
 ],
 "group": 1,
 "level": 1
};




update();
function update() {
  var nodes = flatten(root),
      links = d3.layout.tree().links(nodes);

  // Restart the force layout.
  force
      .nodes(nodes)
      .links(links)
      .start();

  // Update links.
  link = link.data(links, function(d) { return d.target.id; });

  link.exit().remove();

  link.enter().insert("line", ".node")
      .attr("class", "link");

  // Update nodes.
  node = node.data(nodes, function(d) { return d.id; });

  node.exit().remove();

  var nodeEnter = node.enter().append("g")
      .attr("class", "node")
      .on("click", click)
      .call(force.drag);

  nodeEnter.append("circle")
      .attr("r", function(d) { return 1.0/ d.level * 40; });

  nodeEnter.append("text")
      .attr("dy", ".35em")
      .text(function(d) { return d.name; });

  node.select("circle")
      .style("fill", function(d) {var current_color = color(d.group); console.log(current_color); return current_color;});
}

function tick() {
  link.attr("x1", function(d) { return d.source.x; })
      .attr("y1", function(d) { return d.source.y; })
      .attr("x2", function(d) { return d.target.x; })
      .attr("y2", function(d) { return d.target.y; });

  node.attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; });
}




function showcontent(d) {
    var content_div = document.getElementById("1");
    content_div.innerHTML = ""; // clear
    var tmpcontent_element = generate_d_element(d)
    content_div.appendChild(tmpcontent_element);
}



function generate_d_element (d) {
  var container = document.createElement('div');
  container.className = "col-md-4";
  var button_container = document.createElement('p');
  var button = document.createElement('a');
  button.className = "btn btn-secondary";
  button.innerHTML = "Plunge deeper into " + d.name;
  button.setAttribute("href", "{{url_for('searcher.search_keyword')}}" + d.name);
  button.setAttribute("role", "button");
  button_container.appendChild(button);
  container.appendChild(button_container);
  return container;
}


function showresult(d) {
    var data = {
    data: JSON.stringify({
      "name": d.name
    })
  };
  $.ajax({
      url: "/search_keyword" ,
      type: "POST",
      data: data,
      dataType: 'json',
      success: function(data) {
      },
      error: function(xhr, type) {
        console.log("error", xhr, type);
      }
  });
}

// Toggle children on click.
function click(d) {
  if (d3.event.defaultPrevented) return; // ignore drag
  if (d.children) {
    d._children = d.children;
    d.children = null;
  } else {
    d.children = d._children;
    d._children = null;
  }
  update();
  if (d.name != "Concepts") {
        showcontent(d);
  }
}

// Returns a list of all nodes under the root.
function flatten(root) {
  var nodes = [], i = 0;

  function recurse(node) {
    if (node.children) node.children.forEach(recurse);
    if (!node.id) node.id = ++i;
    nodes.push(node);
  }

  recurse(root);
  return nodes;
}

</script>
{% endblock %}